/* src/common/config.h.  Generated by configure.  */

#ifndef _CONFIG_H_
#define _CONFIG_H_

// compiler keywords and attributes
/* #undef inline */
#define HAVE_INLINE 1
#define HAVE___INLINE__ 1
#define HAVE___INLINE 1
/* #undef HAVE___FORCEINLINE */
#define HAVE_ATTRIBUTE_NOINLINE 1
#define HAVE_ATTRIBUTE_ALWAYS_INLINE 1
#define HAVE_ATTRIBUTE_GNU_INLINE 1

// headers
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_SELECT_H 1
/* #undef HAVE_EXECINFO_H */
/* #undef HAVE_NET_SOCKET_H */

// functions
#define HAVE_SETRLIMIT 1
#define HAVE_STRNLEN 1
#define HAVE_GETPID 1
/* #undef HAVE_GETTID */

// other
/* #undef PACKETVER */

#endif /* _CONFIG_H_ */
